---
title: "herringr-carbonate"
author: "Kate Morkeski"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

Libraries used

```{r}

library(here)
#library(readxl)
library(tidyverse)

```

# Read in carbonate data

```{r}

dicta <- read_csv(here('herringriv_carbonate_summary.csv'), show_col_types = FALSE) 

dicta$Date <- as.Date(dicta$Date, format = "%m/%d/%Y")  

dicta$Treatment <- as.factor(dicta$Treatment)

```

# Organize data

```{r}

dicta$Sample_ID <- gsub("22-", "", dicta$Sample_ID)
dicta$Sample_ID <- as.integer(dicta$Sample_ID)
dicta <- dicta[order(dicta$Sample_ID),]

dicta$Month <- format(dicta$Date, "%m")

dicta <- dicta %>% mutate(Spur = case_when(Plot > 7 ~ "creek",
                                       Plot < 8 ~ "woods"))

dicta_Aug <- dicta %>% filter(Month == '08')

dicta_Aug_5 <- dicta_Aug %>% filter(Depth_cm == 5)
dicta_Aug_15 <- dicta_Aug %>% filter(Depth_cm == 15)
dicta_Aug_sand <- dicta_Aug %>% filter(Depth_cm == 3)

dicta_15 <- dicta %>% filter(Depth_cm == 15)

```

# Plot 5 cm data

```{r}

#trt_colors <- c()

ggplot(dicta_Aug_5, aes(Salinity_psu, DIC_umol_kg, color = Spur)) + geom_point(size = 4)
ggplot(dicta_Aug_5, aes(Salinity_psu, DIC_umol_kg, color = Treatment)) + geom_point(size = 4)

ggplot(dicta_Aug_5, aes(Salinity_psu, TA_umol_kg, color = Spur)) + geom_point(size = 4)
ggplot(dicta_Aug_5, aes(Salinity_psu, TA_umol_kg, color = Treatment)) + geom_point(size = 4)

# these two are plotting sums, need to plot averages
#ggplot(dicta_Aug_5, aes(Treatment, Salinity_psu)) + geom_col()  
#ggplot(dicta_Aug_5, aes(Treatment, dicta_umol_kg)) + geom_col()

ggplot(dicta_Aug_5, aes(Treatment, Salinity_psu)) + geom_boxplot()  

ggplot(dicta_Aug_5, aes(Treatment, DIC_umol_kg)) + geom_boxplot()

ggplot(dicta_Aug_5, aes(Treatment, TA_umol_kg)) + geom_boxplot()

ggplot(dicta_Aug_5, aes(Treatment, pH)) + geom_boxplot()

#ggplot(dicta_Aug_5, aes(Treatment, Salinity_psu)) + geom_col() + geom_errorbar(ymin = min(dicta_Aug_5$Salinity_psu), ymax = max(dicta_Aug_5$Salinity_psu))
# x, ymax, ymin, alpha, color, group, linetype, size, width

ggplot(dicta_Aug_5, aes(TA_umol_kg, DIC_umol_kg, color = Treatment)) + geom_point(size = 4)

```
Plot sand layer data

```{r}

ggplot(dicta_Aug_sand, aes(Salinity_psu, DIC_umol_kg, color = Treatment)) + geom_point(size = 4)
ggplot(dicta_Aug_sand, aes(Salinity_psu, TA_umol_kg, color = Treatment)) + geom_point(size = 4)

# these two are plotting sums, need to plot averages
#ggplot(dicta_Aug_sand, aes(Treatment, Salinity_psu)) + geom_col()  
#ggplot(dicta_Aug_sand, aes(Treatment, dicta_umol_kg)) + geom_col()

ggplot(dicta_Aug_sand, aes(Treatment, Salinity_psu)) + geom_boxplot()  

ggplot(dicta_Aug_sand, aes(Treatment, DIC_umol_kg)) + geom_boxplot()
ggplot(dicta_Aug_sand, aes(Treatment, TA_umol_kg)) + geom_boxplot()

ggplot(dicta_Aug_sand, aes(Treatment, pH)) + geom_boxplot()

```
Plot 15 cm data

```{r}

ggplot(dicta_Aug_15, aes(Salinity_psu, DIC_umol_kg, color = Treatment)) + geom_point(size = 4)
ggplot(dicta_15, aes(Salinity_psu, DIC_umol_kg, color = Treatment)) + geom_point(size = 4)
ggplot(dicta_15, aes(Salinity_psu, DIC_umol_kg, color = Spur)) + geom_point(size = 4)
ggplot(dicta_15, aes(Salinity_psu, DIC_umol_kg, color = Month)) + geom_point(size = 4)

ggplot(dicta_Aug_15, aes(Salinity_psu, TA_umol_kg, color = Treatment)) + geom_point(size = 4)
ggplot(dicta_15, aes(Salinity_psu, TA_umol_kg, color = Treatment)) + geom_point(size = 4)
ggplot(dicta_15, aes(Salinity_psu, TA_umol_kg, color = Spur)) + geom_point(size = 4)
ggplot(dicta_15, aes(Salinity_psu, TA_umol_kg, color = Month)) + geom_point(size = 4)

```



